# Currently supported compilers:
# gcc, mingw gcc, clang, MSVC, clang-cl
set(CMCC_IS_GCC OFF)
set(CMCC_IS_MINGW-GCC OFF)
set(CMCC_IS_CLANG OFF)
set(CMCC_IS_MSVC OFF)
set(CMCC_IS_CLANG-CL OFF)

if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
  if(MINGW)
    set(CMCC_IS_MINGW ON)
    message("   -> Using compiler config: MINGW GCC")
  else()
    set(CMCC_IS_GCC ON)
    message("   -> Using compiler config: GCC")
  endif()
elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
  if("${CMAKE_CXX_SIMULATE_ID}" STREQUAL "MSVC")
    set(CMCC_IS_CLANG-CL ON)
    message("   -> Using compiler config: CLANG-CL")
  else()
    set(CMCC_IS_CLANG ON)
    message("   -> Using compiler config: CLANG")
  endif()
elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
  set(CMCC_IS_MSVC ON)
  message("   -> Using compiler config: MSVC")
else()
  message(FATAL_ERROR "Unsupported compiler!")
endif()
